pipeline {
   agent any
   parameters {
        choice(name: 'environment', choices: ['DEV', 'ACCEPTANCE', 'STAGING', 'PRODUCTION'], description: 'Please choose environment')
    }
   stages{
    stage('cloudfront-cache-invalidation'){
      environment { 
         AWS_ACCESS_KEY_ID = credentials("${params.environment}-ACCESS-KEY-ID")
         AWS_SECRET_ACCESS_KEY = credentials("${params.environment}-SECRET-ACCESS-KEY") 
      }
      steps{
        script{
            cmd = "aws cloudfront list-distributions | jq '.DistributionList.Items[]|[ .Id ] | @tsv ' -r"
            def list = sh(script: cmd, returnStdout: true)
            writeFile file: 'cloudfront_ids.txt', text: list
            def distributionids = readFile("cloudfront_ids.txt").readLines()
            for(distributionid in distributionids){
                create_cmd = """aws cloudfront create-invalidation --distribution-id $distributionid --paths "/*" | jq -r .Invalidation.Id"""
                INVALIDATION_ID = sh(script: create_cmd, returnStdout: true)
                wait_cmd = """aws cloudfront wait invalidation-completed --distribution-id $distributionid --id $INVALIDATION_ID"""
                sh(wait_cmd)
            }
        }
      }
    }
   }
}
